# Generated by Django 3.1.3 on 2020-11-27 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stockchecker', '0003_auto_20201126_0943'),
    ]

    operations = [
        migrations.CreateModel(
            name='チーズ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('商品名', models.CharField(max_length=200)),
                ('dis_date', models.DateTimeField(verbose_name='賞味')),
                ('category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='stockchecker.categorys')),
            ],
            options={
                'verbose_name': 'チーズ',
                'verbose_name_plural': 'チーズ',
            },
        ),
    ]
